package br.com.sedeug.clearfiles;
import java.io.File;
import java.io.FileFilter;
import java.io.IOException;
import java.math.BigInteger;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.Comparator;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import s.lib.TFile;
import s.lib.THash;
import s.lib.TUtil;

/**

 @author Cristhian Guedes
 */
public class Main extends javax.swing.JFrame{
  /** Creates new form Main */
  public Main(){
    initComponents();
  }
  /** This method is called from within the constructor to
   initialize the form.
   WARNING: Do NOT modify this code. The content of this method is
   always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    __buildClearCB = new javax.swing.JCheckBox();
    jButton1 = new javax.swing.JButton();
    __buildFolderName = new javax.swing.JTextField();
    jScrollPane1 = new javax.swing.JScrollPane();
    __message = new javax.swing.JTextArea();
    jButton2 = new javax.swing.JButton();
    jButton3 = new javax.swing.JButton();
    __sourcePath = new javax.swing.JTextField();
    jButton4 = new javax.swing.JButton();
    jButton5 = new javax.swing.JButton();
    __only1 = new javax.swing.JCheckBox();
    __pattern = new javax.swing.JTextField();
    jButton6 = new javax.swing.JButton();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

    jButton1.setText("Apagar");
    jButton1.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButton1ActionPerformed(evt);
      }
    });

    __buildFolderName.setText("\\build\\");

      __message.setColumns(20);
      __message.setRows(5);
      jScrollPane1.setViewportView(__message);

      jButton2.setText("Checar duplicados");
      jButton2.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
          jButton2ActionPerformed(evt);
        }
      });

      jButton3.setText("Apagar duplicados");
      jButton3.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
          jButton3ActionPerformed(evt);
        }
      });

      __sourcePath.setText("D:\\GoogleDrive_CristhianGuedes\\");

        jButton4.setText("CheckFolderSize");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
          public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton4ActionPerformed(evt);
          }
        });

        jButton5.setText("jButton5");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
          public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton5ActionPerformed(evt);
          }
        });

        __only1.setSelected(true);
        __only1.setText("Only");

        __pattern.setText(" (1)");

        jButton6.setText("NewStructureFolder");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
          public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton6ActionPerformed(evt);
          }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
          layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
              .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addGroup(layout.createSequentialGroup()
                    .addComponent(__buildFolderName, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(__buildClearCB)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jButton1))
                  .addComponent(jButton5))
                .addGap(0, 41, Short.MAX_VALUE))
              .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(jScrollPane1)
              .addGroup(layout.createSequentialGroup()
                .addComponent(__only1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(__pattern, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))))
          .addComponent(__sourcePath)
        );
        layout.setVerticalGroup(
          layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
            .addComponent(__sourcePath, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
              .addComponent(jButton2)
              .addComponent(jButton3)
              .addComponent(__only1)
              .addComponent(__pattern, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
              .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(__buildClearCB)
                    .addComponent(__buildFolderName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                  .addGroup(layout.createSequentialGroup()
                    .addGap(2, 2, 2)
                    .addComponent(jButton1)))
                .addGap(47, 47, 47)
                .addComponent(jButton4)
                .addGap(18, 18, 18)
                .addComponent(jButton5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 207, Short.MAX_VALUE)
                .addComponent(jButton6)
                .addGap(156, 156, 156))))
        );

        pack();
      }// </editor-fold>//GEN-END:initComponents

  private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    if(__buildClearCB.isSelected()){
      _deletedFilesMessageArray.clear();
      clearFiles(__buildFolderName.getText(), true);
      showMessage("Arquivos apagados");
    }
  }//GEN-LAST:event_jButton1ActionPerformed

  private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
    _deletedFilesMessageArray.clear();
    _mapOrigin.clear();
    __message.setText("");
    _duplicatedList.clear();
    checkDuplicatedFilesSamePath();
  }//GEN-LAST:event_jButton2ActionPerformed

  private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
    String str = __message.getText();
    String[] list = str.split("\r\n");
    for(String s : list){
      File f = new File(s);
      deleteFileAndItsParent(f);
    }

    showMessage("Arquivos apagados");
  }//GEN-LAST:event_jButton3ActionPerformed

  private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
    checkFolders(new File(__sourcePath.getText()));
  }//GEN-LAST:event_jButton4ActionPerformed

  private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
//    String _1MB = "1048576";
//    BigInteger big1MB = new BigInteger(_1MB);
//    System.out.println("Check 1MB: "+TUtil.longToFileSize(      big1MB));
//    BigInteger big500MB = new BigInteger("500").multiply(big1MB);
//    BigInteger big512MB = new BigInteger("512").multiply(big1MB);
//    System.out.println("Check 500M: "+TUtil.longToFileSize(             big500MB));
//    System.out.println("Check 512M: "+TUtil.longToFileSize(             big512MB));
//    BigInteger big1GB = new BigInteger("1024").multiply(big1MB);
//    System.out.println("Check 1G: "+TUtil.longToFileSize(   big1GB));
//    BigInteger big1GB_plus_512MB = new BigInteger("1610612736");
//    System.out.println("Check 1G+512MB: "+TUtil.longToFileSize(   big1GB.add(big512MB))); //1610612736
//    System.out.println("Check menos de 1K: "+TUtil.longToFileSize(  new BigInteger("1000")));
//    System.out.println("Check mais de 1K: "+TUtil.longToFileSize(   new BigInteger("2000")));
//    System.out.println("Check 10K: "+TUtil.longToFileSize(         new BigInteger("10240")));
//    System.out.println("Check 10M: "+TUtil.longToFileSize(      new BigInteger("10485760")));
//    
//    System.out.println("Check 10T: "+TUtil.longToFileSize(new BigInteger("10995116277760")));

  }//GEN-LAST:event_jButton5ActionPerformed

  private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
    File f = new File("D:\\GoogleDrive_CristhianGuedes");
    createNewStructureFolder(f);

  }//GEN-LAST:event_jButton6ActionPerformed
  private void deleteFileAndItsParent(File f){

    deleteRecursively(f);

  }
  /**
   @param args the command line arguments
   */
  public static void main(String args[]){
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
     For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
     */
    try{
      for(javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()){
        if("Nimbus".equals(info.getName())){
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    }catch(ClassNotFoundException ex){
      java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }catch(InstantiationException ex){
      java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }catch(IllegalAccessException ex){
      java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }catch(javax.swing.UnsupportedLookAndFeelException ex){
      java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable(){
      public void run(){
        new Main().setVisible(true);
      }
    });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JCheckBox __buildClearCB;
  private javax.swing.JTextField __buildFolderName;
  private javax.swing.JTextArea __message;
  private javax.swing.JCheckBox __only1;
  private javax.swing.JTextField __pattern;
  private javax.swing.JTextField __sourcePath;
  private javax.swing.JButton jButton1;
  private javax.swing.JButton jButton2;
  private javax.swing.JButton jButton3;
  private javax.swing.JButton jButton4;
  private javax.swing.JButton jButton5;
  private javax.swing.JButton jButton6;
  private javax.swing.JScrollPane jScrollPane1;
  // End of variables declaration//GEN-END:variables
  ArrayList<String> _deletedFilesMessageArray = new ArrayList<>();
  private void clearFiles(final String fileName_, final boolean onlyFolder_){
    final File f = new File(__sourcePath.getText());
    final File myFolder = f.getAbsoluteFile();
    File[] myFileList = myFolder.listFiles();
    if(myFileList!=null){
      for(final File fileHere : myFileList){
        checkFolderToDelete(fileHere, fileName_, onlyFolder_);
      }
    }
  }
  private void checkFolderToDelete(final File fileHere_, final String fileName_, final boolean onlyFolder_){
    logCheck(fileHere_);
    if(fileHere_.getAbsolutePath().contains(fileName_)){
      if((onlyFolder_&&fileHere_.isDirectory())||fileHere_.isFile()){
        deleteRecursively(fileHere_);
      }
    }else{
      File[] insideFileList = fileHere_.listFiles();
      if(insideFileList!=null){
        for(File fileInside : insideFileList){
          checkFolderToDelete(fileInside, fileName_, onlyFolder_);
        }
      }
    }
  }
  private void deleteRecursively(final File del_){
    if(del_.isDirectory()){
      final File[] insideList = del_.listFiles();
      if(insideList!=null){
        for(final File f : insideList){
          deleteRecursively(f);
        }
      }
    }
    File parent = del_.getParentFile();
    log_delete(del_);
    del_.delete();
    if(parent.list()==null){
      System.err.println("PARENT IS NULL AT " + parent.getAbsolutePath());
    }
    if(parent.list()!=null&&parent.list().length==0){
      deleteFileAndItsParent(parent);
    }
  }
  private void showMessage(final String message_){
    JOptionPane.showMessageDialog(rootPane, message_);
    __message.setText("");
    for(String str : _deletedFilesMessageArray){
      __message.append(str+"\r\n");
    }
  }
  private void checkDuplicatedFilesSamePath(){
    _deletedFilesMessageArray.clear();
    if(!__sourcePath.getText().equals("")){
      final File f = new File(__sourcePath.getText());
      logCheck(f);
      clearDuplicatedFilesSamePath(f);
      showMessage("Lista de arquivos duplicados encontrados");
      __message.setText("");
      for(File del : _duplicatedList){
        __message.append(del.getAbsolutePath()+"\r\n");
      }
    }else{
      JOptionPane.showMessageDialog(rootPane, "Endereço nulo");
    }
  }
  HashMap<String, File> _mapOrigin = new HashMap<>();
  ArrayList<File> _duplicatedList = new ArrayList<>();
  private void clearDuplicatedFilesSamePath(File f){
    if(f.getName().contains(".tmp.drivedownload")){
      return;
    }
    if(f.getName().contains(".tmp.driveupload")){
      return;
    }
    final File myFolder = f.getAbsoluteFile();
    File[] myFileList = myFolder.listFiles();
    if(myFileList!=null){
      for(final File filesInside : myFileList){
        //logCheck(filesInside);
        if(filesInside.isFile()){
          if(filesInside.getName().equals("desktop.ini")){
            deleteRecursively(filesInside);
          }else{
            String md5 = THash.generateMD5(filesInside);
            if(_mapOrigin.containsKey(md5)){
              File previous = _mapOrigin.get(md5);
              String copy = "";
              String pattert = __pattern.getText();
              if(pattert.trim().equals("")){
                pattert = " (1)";//duplicado pelo google drive
              }
              if(filesInside.getAbsolutePath().contains(pattert)){
                _duplicatedList.add(filesInside);
                copy = ("------------------->ORIGIN: "+filesInside.getAbsolutePath())+"\r\n"
                       +("------------------->COPY__: "+previous.getAbsolutePath());
                System.err.println(copy);
              }else{
                if(__only1.isSelected()){
                  if(previous.getAbsolutePath().contains(pattert)){
                    _duplicatedList.add(previous);
                    _mapOrigin.remove(previous);
                    _mapOrigin.put(md5, filesInside);
                    copy = ("------------------->ORIGIN: "+filesInside.getAbsolutePath())+"\r\n"
                           +("------------------->COPY__: "+previous.getAbsolutePath());
                    System.err.println(copy);
                  }
                }else{
                  _duplicatedList.add(previous);
                  _mapOrigin.remove(previous);
                  _mapOrigin.put(md5, filesInside);
                  copy = ("------------------->ORIGIN: "+filesInside.getAbsolutePath())+"\r\n"
                         +("------------------->COPY__: "+previous.getAbsolutePath());
                  System.err.println(copy);
                }
              }

            }else{
              _mapOrigin.put(md5, filesInside);
            }
          }
        }else{
//          if(filesInside.getName().contains("CustomPrinter")){
//            System.out.println("break");
//            
//          }
          if(filesInside.listFiles().length==0){
            System.out.print("EMPTY_FOLDER:");
            deleteRecursively(filesInside);
          }else{
            clearDuplicatedFilesSamePath(filesInside);
          }
        }
      }
    }

  }
  private void logCheck(final File fileHere_){
    if(fileHere_.isDirectory()){
      //System.out.println("CHECK_FOLDER: "+fileHere_.getAbsolutePath());
    }else{
      //System.out.println("CHECK_FILE__: "+fileHere_.getAbsolutePath());
    }
  }
  private void log_delete(final File del_){
    String message;
    if(del_.isDirectory()){
      message = ("DELETE_FOLDER:"+del_.getAbsolutePath());
    }else{
      message = ("DELETE_FILE__:"+del_.getAbsolutePath());
    }
    _deletedFilesMessageArray.add(message);
    System.out.println(message);
  }
  ArrayList<FolderSize> _listFolderSize = new ArrayList<>();
  private void checkFolders(File parent){
    _listFolderSize.clear();
    File[] listedFiles = parent.listFiles();
    //String message = "";
    for(File folder : listedFiles){
      if(folder.isDirectory()){
        BigInteger fileSize = checkFolderSize(folder);
        FolderSize fd = new FolderSize(folder, fileSize);
        _listFolderSize.add(fd);
        //String res = (folder.getAbsolutePath()+": "+TUtil.longToFileSize(fileSize)+"\r\n");
        //message += res;//
        //System.err.print(res);
      }
    }
    //__message.setText(message);

    _listFolderSize.sort(new Comparator<FolderSize>(){
      @Override
      public int compare(FolderSize o1_, FolderSize o2_){
        return o1_.compareTo(o2_);
      }
    });
    __message.setText("");
    for(FolderSize fd : _listFolderSize){
      String res = (fd.getAbsolutePath()+": "+fd.getFileSizeFormatted()+"\r\n");
      __message.append(res);
    }
  }
  private BigInteger checkFolderSize(File drive){
    File[] folFile = drive.listFiles();
    BigInteger bigResult = new BigInteger("0");
    for(File folder : folFile){
      BigInteger size = new BigInteger(""+chechSizeRecursively(folder));
      String result = (folder.getName()+" size "+TUtil.longToFileSize(size)+"\r\n");
      bigResult = bigResult.add(size);
      System.out.print("Checked: "+result);
    }
    return bigResult;
  }
  private long chechSizeRecursively(File folder_){
    long size = 0;
    if(folder_.isDirectory()){
      File[] list = folder_.listFiles();
      for(File f : list){
        if(f.isDirectory()){
          size += chechSizeRecursively(f);
        }else{
          size += f.length();
        }
      }
      return size;
    }else{
      return folder_.length();
    }
  }
  private void createNewStructureFolder(File drive_){
    File[] fileList = drive_.listFiles();
    for(File file : fileList){
      //System.out.println("FROM: "+file);
      if(file.isFile()){
        renameFile(file);
      }else{
        createNewStructureFolder(file);
      }
    }
  }
  private void renameFile(File file){
    if(!file.getName().contains(".tmp.drive")){
      System.out.println("");
      String path = file.getAbsolutePath();
      path = path.replace("D:\\GoogleDrive_CristhianGuedes\\", "");
      String[] pathList = path.split("\\\\");
      for(int i = 0; i<pathList.length-1; i++){
        if(pathList[i].startsWith("X")){
          pathList[i] = pathList[i].substring(1);
        }else{
          pathList[i] = pathList[i];
        }

      }
      String newPath = "D:\\GoogleDrive_CristhianGuedes";
      for(int i = 0; i<pathList.length-1; i++){
        newPath = newPath+"\\"+pathList[i];
      }

      try{

        boolean created = TFile.createDir(newPath);
        File newDir = new File(newPath);
        if(created||(newDir.exists()&&newDir.isDirectory())){
          //System.out.println("DIR_CREATED: " + newPath);
          newPath = newPath+"\\"+pathList[pathList.length-1];
          //System.out.println("WillMoveFile: " + file.getAbsolutePath());
          boolean rename = file.renameTo(new File(newPath));
          if(rename){
            //System.out.println("Moved OK");
          }else{
            System.err.println("ERROR ON MOVING FILE"+file.getAbsolutePath());
          }
        }else{
          System.err.println("ERROR ON CREATE PATH FOR "+newPath);
        }
      }catch(IOException ex){
        Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
      }
//      System.out.println("NewPathList is " + newPath);
//      path = "D:\\GoogleDrive_CristhianGuedes\\X"+path;
//      System.out.println("TO__: "+path);
//      File parent = file.getParentFile();
//      parent = parent.getParentFile();
//      System.out.println("Parent is "+parent);
    }else{
      System.err.println("DriveFile "+file.getAbsolutePath());
    }

  }
}
